### ISSUE TITLE
overscroll() occasionally not working when loading / reloading a page

### ISSUE THREAD

**Issue by derjochenmeyer** [azoff/overscroll#66]
Thanks for this plugin! I love it.

However, sometimes (occasionally) when I load (Firefox 14.0.1 WIN) or reload (Chrome 21.0.1180.75 m WIN) the page overscroll() does not "fire". There are NO console errors. Activating overscroll() manually clicking a link `<a href="javascript:$("#canvas").overscroll()">enable scrolling</a>`works fine.

Here's my raw setup_

JavaScript

``` javascript
$(document).ready(function() {
  $("#canvas").overscroll();
});
```

HTML

``` html
<div id="canvas">
  <div id="tile-handlers">[100 handlers]</div>
  <div id="tile-images">[100 images]</div>
</div>
```

CSS

``` css
#canvas {
  position: relative;
  width: 940px;
  height: 400px;
  overflow: scroll;
}
```
